// src/constants/texts.ts
// Centralized file for hardcoded <Text> component strings used in the project

export const TEXTS = {
  // General
  CANCEL: 'Cancel',
  CONFIRM: 'Confirm',
  ADD_WALLET: 'Add Wallet',
  CREATE_WALLET: 'Create Wallet',
  IMPORT_WALLET: 'Import Wallet',
  GET_STARTED: 'Get Started',
  PASTE: 'Paste',
  CHAIN_TYPE: 'Chain Type',
  WALLET_NAME: 'Wallet Name',
  PASSWORD: 'Password',
  PASS_PHRASE: 'Passphrase',
  SET_PASSWORD: 'Set Password',
  REPEAT_NEW_PASSWORD: 'Repeat New password',
  NEXT: 'Next',
  COPY_PRIVATE_KEY: 'Copy Private Key',
  DELETE_WALLET: 'Delete Wallet',
  EXPORT_PRIVATE_KEY: 'Export Private Key',
  MODIFY_PASSWORD: 'Modify Password',
  RESET_PASSWORD: 'Reset Password',
  HOME_TOKEN: 'Home Token',
  CUSTOM_TOKEN: 'Custom Token',
  MY_TOKENS: 'MY Tokens',
  ASSET_LIST: 'Asset List',
  HOT_TOKENS: 'HOT Tokens',
  MY_NFT: 'My NFT',
  ALL_NFT: 'All NFT',
  CUSTOM_NFT: 'Custom NFT',
  HOT_NFT: 'Hot NFT',
  ADD_NFT: 'Add NFT',
  SEND: 'Send',
  RECEIVE: 'Receive',
  BUY: 'Buy',
  TERMS_OF_SERVICE: 'Terms of Service',
  I_HAVE_READ_AND_AGREE: 'I have read and agree ',
  COMING_SOON: 'Coming Soon...',
  IMPORTANT: 'Important',
  BACKUP_RECOVERY_PHRASE: 'Backup Recovery Phrase',
  SUGGESTED_BACKUP_METHOD: 'Suggested Backup Method',
  UNDERSTOOD: 'Understood',
  SUBMIT: 'Submit',
  COMPLETE: 'Complete',
  REMEMBER: 'Remember:',
  GENERATE_MNEMONIC: 'Generate Mnemonic',
  TRADING_DATA: 'Trading Data',
  TIME: 'Time',
  PRICE: 'Price',
  PRICE_ETH: 'Price(&)',
  AMOUNT: 'Amount',
  AMOUNT_BNB: 'Amount(BNB)',
  VALUE: 'Value',
  VALUE_USD: 'Value($)',
  ADDRESS: 'Address',
  HOLDER_TOP10: 'Holder(Top10)',
  AMOUNT_RATIO: 'Amount(Ratio)',
  TRANSACTIONS: 'Transactions',
  NAME: 'Name',
  LAST_PRICE: 'Last Price',
  CHANGE_PERCENT: 'Change(%)',
  RATIO: 'Ratio',
  POSITION_BNB: 'Position(BNB)',
  CHG_24H: '24H Chg',
  HD_WALLET: 'HD Wallet',
  SINGLE_NETWORK: 'Single Network',
  USER_AGREEMENT: 'User Agreement',
  PASSWORD_HINT_OPTIONAL: 'Password hint (Optional)',
  CONFIRM_PASSWORD: 'Confirm Password',
  THE_PASSWORD_IS_NOT_MATCH: 'The password is not match',
  THE_WALLET_NAME_MISSING: 'The wallet name missing',
  EDIT: 'Edit',
  SET_NAME: 'Set Name',
  NOTE: 'Note',
  SAVE: 'Save',
  CHOOSE_A_NETWORK: 'Choose a network',
  CHOOSE_A_WALLET: 'Choose a Wallet',
  MANAGE_WALLETS: 'Manage Wallets',
  ADDRESS_BOOK: 'Address Book',
  SETTINGS: 'Settings',
  MARKET_SETTINGS: 'Market Settings',
  GREEN_UP_RED_DOWN: 'Green Up, Red Down',
  RED_UP_GREEN_DOWN: 'Red Up, Green Down',
  INVITE_FRIEND: 'Invite Friend',
  INVITE_YOUR_FRIEND: 'Invite your friend to use TGwallet',
  TGWALLET: 'TGwallet',
  SCAN_DOWNLOAD: 'Scan & Download',
  COPY: 'Copy',
  SHARE: 'Share',
  KEYPAL_CARD: 'KeyPal Card',
  RECOVERY_PHRASE: 'Recovery Phrase',
  PRIVATE_KEY: 'Private Key',
  WATCH_WALLET: 'Watch Wallet',
  FROM: 'From : ',
  TO: 'To : ',
  VALUE_COLON: 'Value : ',
  BALANCE: 'Balance',
  PLAIN_TEXT_12: 'Plain text (12 words)',
  SHOW_QR_CODE: 'Show QR Code',
  COPY_SECRET_RECOVERY_PHRASE: 'Copy secret recovery phase',
  TAP_TO_DISPLAY_RECOVERY_PHRASE: 'Tap to display recovery phrase',
  TAP_TO_DISPLAY_PRIVATE_KEY: 'Tap to display private key',
  WALLET_ADDRESS: 'Wallet Address',
  EXPORT_PRIVATE_KEY_TITLE: 'Export Private Key',
  MODIFY_PASSWORD_TITLE: 'Modify Password',
  RESET_PASSWORD_TITLE: 'Reset Password',
  DELETE_WALLET_TITLE: 'Delete Wallet',
  MY_TOKENS_TITLE: 'MY Tokens',
  HOME_TOKEN_TITLE: 'Home Token',
  CUSTOM_TOKEN_TITLE: 'Custom Token',
  HOT_TOKENS_TITLE: 'HOT Tokens',
  MY_NFT_TITLE: 'My NFT',
  ALL_NFT_TITLE: 'All NFT',
  CUSTOM_NFT_TITLE: 'Custom NFT',
  HOT_NFT_TITLE: 'Hot NFT',
  ADD_NFT_TITLE: 'Add NFT',
  SEND_TITLE: 'Send',
  RECEIVE_TITLE: 'Receive',
  BUY_TITLE: 'Buy',
  TERMS_OF_SERVICE_TITLE: 'Terms of Service',
  PRIVACY_POLICY: 'Privacy Policy',
  RATE_US: 'Rate Us',
  OFFICIAL_CHANNELS: 'Official Channels',
  WEBSITE: 'Website',
  TWITTER: 'Twitter',
  TELEGRAM: 'Telegram',
  DISCORD: 'Discord',
  FORUM: 'Forum',
  GITHUB: 'Github',
  EMAIL: 'Email',
  FEEDBACK: 'Feedback',
  LIQUIDITY: 'Liquidty',
  VOL_24H: '24H Vol',
  TXNS_24H: '24H Txns',
  MKT_CAP: 'Mkt Cap',
  TOTAL_SUPPLY: 'Tptal Supply',
  HOLDERS: 'Holders ',
  ABOUT_US: 'About Us',
  VERSION: 'v1.2.3',
  SWAP: 'Swap',
  ADVANCED_SETTINGS: 'Advanced Settings',
  ROUTE_DETAILS: 'Route Details',
  ASSET_LIST_TITLE: 'Asset List',
  HOT_TOKENS_LABEL: 'HOT Tokens',
  HOT_NFT_LABEL: 'Hot NFT',
  SAVE_LABEL: 'Save',
  ADD_LABEL: 'Add',
  CONFIRM_LABEL: 'Confirm',
  NEXT_LABEL: 'Next',
  COMPLETE_LABEL: 'Complete',
  SUBMIT_LABEL: 'Submit',
  UNDERSTOOD_LABEL: 'Understood',
  // Add more as needed from project
};
